### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by pkerling** [NilsBrause/waylandpp#25]
Kodi will be using waylandpp when Wayland support is merged mainline in the next weeks, but waylandpp has not seen a release yet - this makes it hard to depend on it in a predictable way. For instance we cannot even show the user an error message when an incompatible version is used.

I realize that lots of the PRs I did the last months broke API and/or ABI and there may still be some areas that need some more fleshing out, so waylandpp is not exactly "stable" yet probably. But you could release version 0.1 or something :-)

I'll also PR support for pkg-config later this week so the version can be queried.

**Comment by NilsBrause** [comment]
I didn't expect anyone to seriously use waylandpp, let alone a big project such a kodi. I kinda feel honoured now. I always wondered, why you have such a huge interest in it. Now I know. :)

Anyway, a release sounds like a good idea. I have never done that before, though. Should we put a wayland::version() in the library so that it can be checked at runtime?

I will start with version 0.1 as suggested once I merged you pkg-config PR. We can move to version 1.0 once the API is stable for some time. And maybe a 2.0 once the server bindings are ready, that I work on in my limited spare time.

I'm not sure we can easily maintain ABI stability though. But in an open source ecosystem, this isn't a big problem, since the user can just recompile.

**Comment by pkerling** [comment]
Ah, it seems GitHub automatically creates the git tag when you use the button on the [Releases](https://github.com/NilsBrause/waylandpp/releases) page, so probably best to use that.

**Comment by NilsBrause** [comment]
Done. And I'll be using semantic versioning. :)

**Comment by pkerling** [comment]
Awesome! Thanks a bunch. :+1:
