### ISSUE TITLE
Use a different build system

### ISSUE THREAD

**Issue by candrews** [NilsBrause/waylandpp#29]
Can you please use a different build system?
cmake, meson, autotools... anything but scons.

scons is just really horrible to work with... it's nonstandard (every scons project is different) and doesn't do anything automatically (like handle libdir, cc, ldflag, cxxflags, cflags, etc) among other problems.

No distribution is going to be happy having to work with scons, so if you want waylandpp to be packaged in distros and widely distributed (which I think is the point), it's best to use something else.

See https://wiki.gentoo.org/wiki/SCons#Why_you_should_NOT_use_SCons_in_your_project for details.

**Comment by pkerling** [comment]
@NilsBrause I can do it in CMake if you agree and don't have the time yourself

**Comment by NilsBrause** [comment]
I like SCons a lot because it is MUCH more flexible than any other build system out there. Of course this comes at the cost of being at bit more low level, but in my opinion it is totally worth it. BTW: Despite the gentoo wiki claiming the opposite, SCons works perfectly well with SONAMES. Just have a look at my SConstruct file and rtfm.

But there seem to b a lot of novices out there, who seem to have problems with SCons. And even though some of them are pretty stupid calling me a moron (looking at you @SoapGentoo), I want to make everyone happy. Therefore I will accept patches to add a secondary build system alongside SCons.

@pkerling: Go ahead if you want.
